### ISSUE TITLE
num= argument does not support negative numbers and decimal places

### ISSUE THREAD

**Issue by SchmidtPaul** [kwstat/desplot#1]
In Example 2 of the 'desplot' vignette, a heatmap of residuals is plotted. Changing the `text=gen` statement to `num=res` in order to plot the actual values, shows a '1' in the plot that actually has a residual of '-1'. 

library(agridat); library(desplot)
nuts <- ryder.groundnut
mod <- lm(data=nuts, formula= dry ~ block + gen)
nuts$res <- resid(mod)
desplot(data=nuts, form= res ~ col+row, num=res, show.key=F, main="")

![grafik](https://user-images.githubusercontent.com/31928213/46560258-4c72cc00-c8f3-11e8-8412-83f68d20ad71.png)

Furthermore, plotting the yield data of e.g. the john.alpha dataset in the agridat package leads to plotted values that simply seem to ignore the decimal point and therefore seem to disagree with the ribbon.

library(agridat); library(desplot)
alpha<- john.alpha
alpha$row <- rep(4:1)
alpha$col <- sort(rep(seq(18:1),4))
desplot(data=alpha, form= yield ~ col+row, num=yield, show.key=F,  main="")

![grafik](https://user-images.githubusercontent.com/31928213/46560238-40870a00-c8f3-11e8-82f6-ebdc1647a59f.png)

**Comment by kwstat** [comment]
The good news is that this is not a bug. The bad news is that the documentation doesn't make this clear. You want to use text=yield, shorten="none" instead of num=yield.  Allowing show.key=TRUE makes this a bit more obvious.  The "num" argument is intended to show treatments as numbers (with a key), just like the "col" argument" can be used to color treatments with a key.

```library(agridat); library(desplot)
alpha<- john.alpha
alpha$row <- rep(4:1)
alpha$col <- sort(rep(seq(18:1),4))
desplot(data=alpha, form= yield ~ col+row, text=yield, main="", cex=1, shorten="none")
```
I need to think about how to improve the documentation.
