### ISSUE TITLE
Using `| location` for reps with incomplete data

### ISSUE THREAD

**Issue by SchmidtPaul** [kwstat/desplot#6]
Hi, I just realized that x/y coordinates missing in the data are treated differently depending on whether I use the `| location` argument or not:

``` r
library(tidyverse)
library(desplot)

dat <- tibble::tribble(
  ~row, ~col, ~rep, ~id,
    1L,   1L,   1L, "A",
    2L,   1L,   1L, "B",
    1L,   2L,   2L, "C",
    2L,   2L,   2L, "D",
    3L,   2L,   2L, "E"
  )

desplot(dat, 
        id ~ col + row,
        text = id, cex = 1)
```

![](https://i.imgur.com/sEU2M2T.png)

``` r
desplot(dat, 
        id ~ col + row | rep,
        text = id, cex = 1)
```

![](https://i.imgur.com/msGXYxc.png)

I guess this is intended (?), given that the `| location` suggests using this argument for different trials (where it makes sense) and not multiple replicates of the same trial as I am doing here. 
However, if I *do* want to use it for reps of the same trial, then there is no extra argument to make this work, right? I would simply need to add the missing lines of data to the dataset, i.e. have all x-y-combinations as `NA` present. I realize how odd it is in the first place to have field trial data that includes only a subset of all plots, but that's what I received in this case.

Here's the solution I came up with:
``` r
datexp <- expand_grid(
  row = 1:max(dat$row),
  col = 1:max(dat$col)
) %>% 
  left_join(y = dat, by = c("row", "col")) %>% 
  mutate(rep = col)

desplot(datexp,
        id ~ col + row | rep,
        text = id, cex = 1)
```

![](https://i.imgur.com/MGG47RN.png)

<sup>Created on 2022-02-04 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by kwstat** [comment]
I think it is quite common to have blocks with different shapes. Either because of missing data, or orientation of the blocks in the field, or irrigation equipment or roads that run through the field.  It might be possible to do some type of computation on the "aspect ratio" so that all experimental unit plots had the same shape, but I think it will be hard to come up with a general solution that works well in all cases.  Let me know if you have ideas.

One "hack" is to add missing plots, as you have done.  Another hack is to modify the desplot object before printing.  For example, we can specify a common value for `ylim`:

```
d1 <- desplot(dat, 
        id ~ col + row|rep,
        text = id, cex = 1)
d1 <- update(d1, ylim=c(0.5,3.5))
plot(d1)
```
![desplot](https://user-images.githubusercontent.com/484260/152648496-c1d6e6dc-3132-4971-99c7-a9862530c5e2.png)
